<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="image\" />
    <Folder Include="wwwroot\images\Content Gallery\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\images\LOGO.png" />
  </ItemGroup>

</Project>
